### PR TITLE
Small adjustements

### PR DESCRIPTION
**Pull request by babelouest**
better default config, use last versions

### CODE REVIEW

**Comment by rafaelhdr** [comment]
Thanks. Just accepted :)

But about the log_mode, I think it is better to use the console. At the docker, the files are not persisted (by default). But the console is stored (just run `docker logs CONTAINER_ID`). Ok?

**Comment by babelouest** [comment]
Sure, my bad for the console, I didn't know, thanks! :)

**Comment by rafaelhdr** [comment]
Sure. I am also learning :)
It will be an easy fix.

And sorry. I thought I could have more time today =/
But slowly, this project will be finished ;)

**Comment by babelouest** [comment]
No rush to finish it. ;)
But to understand your goals, what do you expect when it will be finished? Do you have a roadmap or a to-do list?

**Comment by rafaelhdr** [comment]
I don't have a deadline. Neither a roadmap, but I do have a to-do list.

- Quickstart with LDAP
- Different build for mysql/sqlite/ldap
- Images with alpine linux
- Custom build with environment variables
- Check best practices
- Automate deploy images (if possible)
- Documentation for SSH keys and password

I was doing the **Images with alpine linux**. But checking again, I think **Documentation for SSH keys and password** is better, so it will be available for production. What do you think?

**Pull request merged**
