### PR TITLE
Docker imags based on Alpine linux

### PR DESCRIPTION
**Pull request by babelouest**
Hello @rafaelhdr ,

Can you take a look at those Docker scripts? It's a first try to build a docker image of Glewlwyd based on alpine linux distribution, The docker images are smaller (~260 MB).

I could get Glewlwyd start properly on my side, but maybe some things are missing

Also, the precompiled image (`alpine/x86_64`) is faster to build since there is less packages to install and only files to copy, but it's hand-made and I don't know if it follow all the Docker guidelines yet.

Before merging this branch to master, I'd like to make sure everything works fine, and also complete the documentation.

### CODE REVIEW

**Comment by rafaelhdr** [comment]
That is awesome. I had problems when I tried install it with Alpine.

Sure. ASAP I will check it. Thanks :)

**Comment by babelouest** [comment]
It was quite long to find all the packages in Alpine corresponding to the one in Debian but after a lot of iterations and coffee, I could make it :)

**Comment by rafaelhdr** [comment]
@babelouest 

It is not working here. On `docker build -t just_testing .` it raised:

`COPY failed: stat /var/lib/docker/tmp/docker-builder666051171/entrypoint.sh: no such file or directory`

Did you forget to add the file `entrypoint.sh`? (at `alpine/(src|x86_64)/entrypoint.sh`)

And why the directory x86_64?

**Comment by babelouest** [comment]
That's right, I forgot I added the last 3 lines before pushing:

```
COPY ["entrypoint.sh", "/"]
EXPOSE 4593
CMD ["/entrypoint.sh"]
```
Because I made the `alpine/src/Dockerfile` as a base image but bot meant to be run, then I used the `*/quickstart`.

Right now I'm trying to generate a pair of key/certificate with gnutls instead of openssl but it's not as easy :/

I'm pushing a entrypoint.sh that will not generate the certificate for now.

**Comment by babelouest** [comment]
To answer your second question, the directory `x86_64` contains a docker image with a binary glewlwyd and its library already compiled, so only binary libraries are installed, not the `-dev` ones.

**Comment by rafaelhdr** [comment]
Thanks :)

Today later I will test it again.

About the `x86_64`, do you think is it possible to build at the Dockerfile? (and do you think is this a good idea?). I normally don't use binaries at GitHub. We could `rm` the files/directories for a smaller image...

**Comment by babelouest** [comment]
Acutlly, to build the `x86_64` image, I first built the `src`, then ran it with bash, and backuped the built libraries in `/usr/local/lib` and the program in `/usr/local/bin/glewlwyd` in a volume.

Then I made a new `Dockerfile` for `x86_64`, in this Dockerfile, I only install the binaries required, not the development packages, and I unpack the libraries, program and webapp in the image.

The `x86_64` is a test to check if it's easier or faster without having to rebuild Glewlwyd. Of course it's platform dependent so there are limitations.
When I talked to Docker users, they told me they usually use binary in their docker images, that's why I tried this.
But it's not mandatory to be in the master branch, I'm not pushing it, just making some experimentations.

**Comment by rafaelhdr** [comment]
This is an excellent idea. I should have done it before.

I've just checked the `rafaelhdr/glewlwyd-oauth2-server` images and they have the source-code (markdown files, and all).

I will later clean them. Maybe keep a development version (with all source code, just for development and tests).

Thanks. You are getting very good at Docker ;)

**Comment by babelouest** [comment]
All right, we have a nice roadmap then! :)

> You are getting very good at Docker

Baby steps, I'm not even at docker-compose yet ;)

**Comment by rafaelhdr** [comment]
Thanks. I've just merged. I made some changes (you can check, it is not many).

Closing and deleting the branch.

**Pull request merged**
